name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - uses: actions/setup-node@v3
          with:
            node-version: 14
      - name: test and check formatting
        run: |
          sbt -v test scalafmtCheckAll
      - name: build uberjar
        run: |
          sbt -v assembly
            - working-directory: ./cdk
              run: |
                npm ci
                npm run lint
                npm test
                npm run synth
      - uses: guardian/actions-riff-raff@v1
        with:
          app: backend-103-julia
          config: |
            stacks:
              - playground
            regions:
              - eu-west-1
            allowedStages:
              - CODE
            deployments:
              cloudformation:
                type: cloud-formation
                app: backend-103-julia
                sources:
                  - Backend103Julia-CODE.template.json
                parameters:
                  amiParameter: AMIBackend103julia
                  amiTags:
                    Recipe: backend-101
                    AmigoStage: PROD
                  templatePath: Backend103Julia-CODE.template.json
               TODO:
                type: autoscaling
                sources:
                  - target/scala-2.13/hello-world.jar
                  - app.service
                parameters:
                  bucket: e.g. deploy-tools-dist
                dependencies:
                  - cloudformation